version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nasa_research
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: