version: '3.8'

services:
  lunar_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nasa_research
    volumes:
      - postgres_data:/var/lib/postgresql/data

  lunar_data_collector:
    build: 
      context: ./applications/lunar_data_collector/
      dockerfile: service.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - lunar_db
    environment:
      PG_ASYNC_DSN: postgresql+asyncpg://postgres:postgres@lunar_db:5432/nasa_research
volumes:
  postgres_data:

  